# Dependencies
markdown            : kramdown
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate"]

# Permalinks
permalink           : pretty

# Setup
title               : KC's
tagline             : ''
description         : '期末考崩潰中 ...Midterm Breakdown'
baseurl             : /

author              : Kuan-Chia Chiu
name                : 'Kuan-Chia Chiu'
url                 : https://ttt50966.github.io/
disqus:
  shortname: ttt50966-github-io
paginate            : 5

# Custom vars
version             : 0.1.0
twitter_username    : ttt50966
github_username     : ttt50966
